package nl.erends.discozoo;

public enum Tile {

    EMPTY,
    PIG,
    RABBIT,
    COW,
    SHEEP,
    HORSE,
    UNICORN,
    MAMMOTH, SABERTOOTH, KANGAROO, PLATYPUS, CROCODILE, KOALA, COCKATOO, TIDDALIK, ECHIDNA, ZEBRA, HIPPO, GIRAFFE, LION, GRYPHON, RHINO, CHICKEN
}
